#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v4
# autospec commit: 3d985eb
#
# Source0 file verified with key 0xD7574483BB57B18D (jr@jriddell.org)
#
Name     : kdsoap-ws-discovery-client
Version  : 0.4.0
Release  : 1
URL      : https://download.kde.org/stable/kdsoap-ws-discovery-client/kdsoap-ws-discovery-client-0.4.0.tar.xz
Source0  : https://download.kde.org/stable/kdsoap-ws-discovery-client/kdsoap-ws-discovery-client-0.4.0.tar.xz
Source1  : https://download.kde.org/stable/kdsoap-ws-discovery-client/kdsoap-ws-discovery-client-0.4.0.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : CC0-1.0 GPL-3.0
Requires: kdsoap-ws-discovery-client-lib = %{version}-%{release}
Requires: kdsoap-ws-discovery-client-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : doxygen
BuildRequires : extra-cmake-modules-data
BuildRequires : kdsoap-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
<!--
SPDX-License-Identifier: GPL-3.0-or-later
-->
# KDSoap WS-Discovery client                {#mainpage}

%package dev
Summary: dev components for the kdsoap-ws-discovery-client package.
Group: Development
Requires: kdsoap-ws-discovery-client-lib = %{version}-%{release}
Provides: kdsoap-ws-discovery-client-devel = %{version}-%{release}
Requires: kdsoap-ws-discovery-client = %{version}-%{release}

%description dev
dev components for the kdsoap-ws-discovery-client package.


%package doc
Summary: doc components for the kdsoap-ws-discovery-client package.
Group: Documentation

%description doc
doc components for the kdsoap-ws-discovery-client package.


%package lib
Summary: lib components for the kdsoap-ws-discovery-client package.
Group: Libraries
Requires: kdsoap-ws-discovery-client-license = %{version}-%{release}

%description lib
lib components for the kdsoap-ws-discovery-client package.


%package license
Summary: license components for the kdsoap-ws-discovery-client package.
Group: Default

%description license
license components for the kdsoap-ws-discovery-client package.


%prep
%setup -q -n kdsoap-ws-discovery-client-0.4.0
cd %{_builddir}/kdsoap-ws-discovery-client-0.4.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1710449129
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1710449129
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kdsoap-ws-discovery-client
cp %{_builddir}/kdsoap-ws-discovery-client-%{version}/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/kdsoap-ws-discovery-client/8287b608d3fa40ef401339fd907ca1260c964123 || :
cp %{_builddir}/kdsoap-ws-discovery-client-%{version}/LICENSES/GPL-3.0-or-later.txt %{buildroot}/usr/share/package-licenses/kdsoap-ws-discovery-client/d2f4aa13872c7286a16003262a345e5c9a49a066 || :
export GOAMD64=v2
GOAMD64=v2
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/KDSoapWSDiscoveryClient/WSDiscoveryClient
/usr/include/KDSoapWSDiscoveryClient/WSDiscoveryProbeJob
/usr/include/KDSoapWSDiscoveryClient/WSDiscoveryServiceAggregator
/usr/include/KDSoapWSDiscoveryClient/WSDiscoveryTargetService
/usr/include/KDSoapWSDiscoveryClient/kdsoap_wsdiscovery_client_version.h
/usr/include/KDSoapWSDiscoveryClient/wsdiscoveryclient.h
/usr/include/KDSoapWSDiscoveryClient/wsdiscoveryclient_export.h
/usr/include/KDSoapWSDiscoveryClient/wsdiscoveryprobejob.h
/usr/include/KDSoapWSDiscoveryClient/wsdiscoveryserviceaggregator.h
/usr/include/KDSoapWSDiscoveryClient/wsdiscoverytargetservice.h
/usr/lib64/cmake/KDSoapWSDiscoveryClient/KDSoapWSDiscoveryClientConfig.cmake
/usr/lib64/cmake/KDSoapWSDiscoveryClient/KDSoapWSDiscoveryClientConfigVersion.cmake
/usr/lib64/cmake/KDSoapWSDiscoveryClient/KDSoapWSDiscoveryClientTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KDSoapWSDiscoveryClient/KDSoapWSDiscoveryClientTargets.cmake
/usr/lib64/libKDSoapWSDiscoveryClient.so

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/KDSoapWSDiscoveryClient/annotated.html
/usr/share/doc/KDSoapWSDiscoveryClient/bc_s.png
/usr/share/doc/KDSoapWSDiscoveryClient/bc_sd.png
/usr/share/doc/KDSoapWSDiscoveryClient/classWSDiscoveryClient-members.html
/usr/share/doc/KDSoapWSDiscoveryClient/classWSDiscoveryClient.html
/usr/share/doc/KDSoapWSDiscoveryClient/classWSDiscoveryClient.png
/usr/share/doc/KDSoapWSDiscoveryClient/classWSDiscoveryProbeJob-members.html
/usr/share/doc/KDSoapWSDiscoveryClient/classWSDiscoveryProbeJob.html
/usr/share/doc/KDSoapWSDiscoveryClient/classWSDiscoveryProbeJob.png
/usr/share/doc/KDSoapWSDiscoveryClient/classWSDiscoveryServiceAggregator-members.html
/usr/share/doc/KDSoapWSDiscoveryClient/classWSDiscoveryServiceAggregator.html
/usr/share/doc/KDSoapWSDiscoveryClient/classWSDiscoveryServiceAggregator.png
/usr/share/doc/KDSoapWSDiscoveryClient/classWSDiscoveryTargetService-members.html
/usr/share/doc/KDSoapWSDiscoveryClient/classWSDiscoveryTargetService.html
/usr/share/doc/KDSoapWSDiscoveryClient/classes.html
/usr/share/doc/KDSoapWSDiscoveryClient/closed.png
/usr/share/doc/KDSoapWSDiscoveryClient/dir_68267d1309a1af8e8297ef4c3efbcdba.html
/usr/share/doc/KDSoapWSDiscoveryClient/doc.svg
/usr/share/doc/KDSoapWSDiscoveryClient/docd.svg
/usr/share/doc/KDSoapWSDiscoveryClient/doxygen.css
/usr/share/doc/KDSoapWSDiscoveryClient/doxygen.svg
/usr/share/doc/KDSoapWSDiscoveryClient/dynsections.js
/usr/share/doc/KDSoapWSDiscoveryClient/files.html
/usr/share/doc/KDSoapWSDiscoveryClient/folderclosed.svg
/usr/share/doc/KDSoapWSDiscoveryClient/folderclosedd.svg
/usr/share/doc/KDSoapWSDiscoveryClient/folderopen.svg
/usr/share/doc/KDSoapWSDiscoveryClient/folderopend.svg
/usr/share/doc/KDSoapWSDiscoveryClient/functions.html
/usr/share/doc/KDSoapWSDiscoveryClient/functions_func.html
/usr/share/doc/KDSoapWSDiscoveryClient/hierarchy.html
/usr/share/doc/KDSoapWSDiscoveryClient/index.html
/usr/share/doc/KDSoapWSDiscoveryClient/jquery.js
/usr/share/doc/KDSoapWSDiscoveryClient/md_README.html
/usr/share/doc/KDSoapWSDiscoveryClient/menu.js
/usr/share/doc/KDSoapWSDiscoveryClient/menudata.js
/usr/share/doc/KDSoapWSDiscoveryClient/minus.svg
/usr/share/doc/KDSoapWSDiscoveryClient/minusd.svg
/usr/share/doc/KDSoapWSDiscoveryClient/nav_f.png
/usr/share/doc/KDSoapWSDiscoveryClient/nav_fd.png
/usr/share/doc/KDSoapWSDiscoveryClient/nav_g.png
/usr/share/doc/KDSoapWSDiscoveryClient/nav_h.png
/usr/share/doc/KDSoapWSDiscoveryClient/nav_hd.png
/usr/share/doc/KDSoapWSDiscoveryClient/open.png
/usr/share/doc/KDSoapWSDiscoveryClient/pages.html
/usr/share/doc/KDSoapWSDiscoveryClient/plus.svg
/usr/share/doc/KDSoapWSDiscoveryClient/plusd.svg
/usr/share/doc/KDSoapWSDiscoveryClient/search/all_0.js
/usr/share/doc/KDSoapWSDiscoveryClient/search/all_1.js
/usr/share/doc/KDSoapWSDiscoveryClient/search/all_2.js
/usr/share/doc/KDSoapWSDiscoveryClient/search/all_3.js
/usr/share/doc/KDSoapWSDiscoveryClient/search/all_4.js
/usr/share/doc/KDSoapWSDiscoveryClient/search/all_5.js
/usr/share/doc/KDSoapWSDiscoveryClient/search/all_6.js
/usr/share/doc/KDSoapWSDiscoveryClient/search/all_7.js
/usr/share/doc/KDSoapWSDiscoveryClient/search/all_8.js
/usr/share/doc/KDSoapWSDiscoveryClient/search/all_9.js
/usr/share/doc/KDSoapWSDiscoveryClient/search/all_a.js
/usr/share/doc/KDSoapWSDiscoveryClient/search/all_b.js
/usr/share/doc/KDSoapWSDiscoveryClient/search/all_c.js
/usr/share/doc/KDSoapWSDiscoveryClient/search/all_d.js
/usr/share/doc/KDSoapWSDiscoveryClient/search/classes_0.js
/usr/share/doc/KDSoapWSDiscoveryClient/search/close.svg
/usr/share/doc/KDSoapWSDiscoveryClient/search/functions_0.js
/usr/share/doc/KDSoapWSDiscoveryClient/search/functions_1.js
/usr/share/doc/KDSoapWSDiscoveryClient/search/functions_2.js
/usr/share/doc/KDSoapWSDiscoveryClient/search/functions_3.js
/usr/share/doc/KDSoapWSDiscoveryClient/search/functions_4.js
/usr/share/doc/KDSoapWSDiscoveryClient/search/functions_5.js
/usr/share/doc/KDSoapWSDiscoveryClient/search/functions_6.js
/usr/share/doc/KDSoapWSDiscoveryClient/search/functions_7.js
/usr/share/doc/KDSoapWSDiscoveryClient/search/functions_8.js
/usr/share/doc/KDSoapWSDiscoveryClient/search/functions_9.js
/usr/share/doc/KDSoapWSDiscoveryClient/search/mag.svg
/usr/share/doc/KDSoapWSDiscoveryClient/search/mag_d.svg
/usr/share/doc/KDSoapWSDiscoveryClient/search/mag_sel.svg
/usr/share/doc/KDSoapWSDiscoveryClient/search/mag_seld.svg
/usr/share/doc/KDSoapWSDiscoveryClient/search/pages_0.js
/usr/share/doc/KDSoapWSDiscoveryClient/search/search.css
/usr/share/doc/KDSoapWSDiscoveryClient/search/search.js
/usr/share/doc/KDSoapWSDiscoveryClient/search/searchdata.js
/usr/share/doc/KDSoapWSDiscoveryClient/splitbar.png
/usr/share/doc/KDSoapWSDiscoveryClient/splitbard.png
/usr/share/doc/KDSoapWSDiscoveryClient/sync_off.png
/usr/share/doc/KDSoapWSDiscoveryClient/sync_on.png
/usr/share/doc/KDSoapWSDiscoveryClient/tab_a.png
/usr/share/doc/KDSoapWSDiscoveryClient/tab_ad.png
/usr/share/doc/KDSoapWSDiscoveryClient/tab_b.png
/usr/share/doc/KDSoapWSDiscoveryClient/tab_bd.png
/usr/share/doc/KDSoapWSDiscoveryClient/tab_h.png
/usr/share/doc/KDSoapWSDiscoveryClient/tab_hd.png
/usr/share/doc/KDSoapWSDiscoveryClient/tab_s.png
/usr/share/doc/KDSoapWSDiscoveryClient/tab_sd.png
/usr/share/doc/KDSoapWSDiscoveryClient/tabs.css
/usr/share/doc/KDSoapWSDiscoveryClient/wsdiscoveryclient_8h_source.html
/usr/share/doc/KDSoapWSDiscoveryClient/wsdiscoveryprobejob_8h_source.html
/usr/share/doc/KDSoapWSDiscoveryClient/wsdiscoveryserviceaggregator_8h_source.html
/usr/share/doc/KDSoapWSDiscoveryClient/wsdiscoverytargetservice_8h_source.html

%files lib
%defattr(-,root,root,-)
/usr/lib64/libKDSoapWSDiscoveryClient.so.0
/usr/lib64/libKDSoapWSDiscoveryClient.so.0.4.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kdsoap-ws-discovery-client/8287b608d3fa40ef401339fd907ca1260c964123
/usr/share/package-licenses/kdsoap-ws-discovery-client/d2f4aa13872c7286a16003262a345e5c9a49a066
